OnlineNotes/Models/Note.cs
using OnlineNotes.Models.Enums;
using OnlineNotes.Models.Interfaces;
using System.ComponentModel.DataAnnotations;

namespace OnlineNotes.Models
{
    public class Note : IAuditable
    {
        public int Id { get; set; }
        public string UserId { get; set; } = null!;
        public string Title { get; set; }
        public string Contents { get; set; }
        // Collection navigation containing dependents
        public ICollection<Comment> Comments { get; } = new List<Comment>();
        public NoteStatus Status { get; set; }
        public ICollection<NoteRating> Ratings { get; } = new List<NoteRating>();
        public float? AvgRating { get; set; }

        // IAuditable properties
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime CreationDate { get; set; }
        public DateTime? ModificationDate { get; set; }

        public Note(string title, string contents, NoteStatus status)
        {
            Title = title;
            Contents = contents;
            Status = status;
        }
    }
}

OnlineNotes/Models/Requests/Note/BaseNoteRequest.cs
using OnlineNotes.Models.Enums;

namespace OnlineNotes.Models.Requests.Note
{
    public class BaseNoteRequest
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public NoteStatus Status { get; set; }
        public string Contents { get; set; }
        public string UserId { get; set; }
    }
}

OnlineNotes/Models/Requests/Note/CreateNoteRequest.cs
using OnlineNotes.Models.Enums;

namespace OnlineNotes.Models.Requests.Note
{
    public class CreateNoteRequest : BaseNoteRequest
    {
        // Code will be added when needed
    }
}

OnlineNotes/Models/Requests/Note/DeleteNoteRequest.cs
namespace OnlineNotes.Models.Requests.Note
{
    public class DeleteNoteRequest : BaseNoteRequest
    {
        // Code will be added when needed
    }
}

OnlineNotes/Models/Requests/Note/EditNoteRequest.cs
using OnlineNotes.Models.Enums;

namespace OnlineNotes.Models.Requests.Note
{
    public class EditNoteRequest : BaseNoteRequest
    {
        public float? AvgRating { get; set; }
    }
}

OnlineNotes/Models/Requests/Note/UploadNoteAttachmentRequest.cs
namespace OnlineNotes.Models.Requests.Note
{
    public class UploadNoteAttachmentRequest : BaseNoteRequest
    {
        public IFormFile File { get; set; }
    }
}

OnlineNotes/Controllers/CommentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineNotes.Models;
using OnlineNotes.Models.Requests.Comments;
using OnlineNotes.Services.CommentsServices;

namespace OnlineNotes.Controllers
{
    [Authorize]
    public class CommentsController : Controller
    {
        private readonly ICommentsService _commentsService;
        private int _noteId;

        public CommentsController(ICommentsService commentsService) // Dependency Injection principle
        {
            _commentsService = commentsService;
        }


        public IActionResult Create(int noteId)
        {
            _noteId = noteId;
            ViewBag.Message = noteId;
            ViewBag.CreationDate = DateTime.Now;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Contents,CreationDate,NoteId")] CreateCommentRequest comment)
        {
            ModelState.Remove("Note"); // navigation property will be set later by EF based on 'NoteId'

            if (ModelState.IsValid)
            {
                var result = await _commentsService.CreateCommentAsync(comment);

                if (result)
                {
                    return RedirectToAction("Details", "Notes", new { id = comment.NoteId });
                }

            }
            return View(comment); // Show the form with validation errors
        }

        public async Task<IActionResult> DeleteAsync(int id)
        {
            var comment = await _commentsService.GetCommentByIdAsync(id);

            if (comment == null)
            {
                return NotFound();
            }

            ViewBag.Id = id;
            ViewBag.Contents = comment.Contents;
            ViewBag.CreationDate = comment.CreationDate;
            return View();
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(DeleteCommentRequest comment)
        {
            int noteId = await _commentsService.GetNoteIdFromCommentId(comment.Id);
            var result = await _commentsService.DeleteCommentAsync(comment);

            if (result && noteId != 0)
            {
                return RedirectToAction("Details", "Notes", new { id = noteId });
            }
            return NotFound();
        }
    }
}

OnlineNotes/Controllers/NotesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineNotes.ExtensionMethods;
using OnlineNotes.Models;
using OnlineNotes.Models.Enums;
using OnlineNotes.Models.Requests.Note;
using OnlineNotes.Services.NotesServices;
using OnlineNotes.Services.OpenAIServices;
using OnlineNotes.Services.RatingServices;
using Microsoft.AspNetCore.Identity;
using OnlineNotes.Exceptions;


namespace OnlineNotes.Controllers
{
    [Authorize] // restricts access to a controller to only authenticated users
    public class NotesController : Controller
    {
        private readonly IOpenAIService _openAIService;
        private readonly INotesService _notesService;
        private readonly INoteRatingService _ratingService;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ILogger<NotesService> _logger;

        public NotesController(IOpenAIService openAIService, INotesService notesService, INoteRatingService ratingService, UserManager<IdentityUser> userManager, ILogger<NotesService> logger)
        {
            _openAIService = openAIService;
            _notesService = notesService;
            _ratingService = ratingService;
            _userManager = userManager;
            _logger = logger;
        }

        // GET: Notes
        public async Task<IActionResult> Index(int page = 1, string? errorMessage = null)
        {
            IdentityUser user = await _userManager.GetUserAsync(User);
            var userId = user.Id;

            // Filtering:
            var notes = await _notesService.GetFilteredNotesToListAsync(_notesService.GetFilterStatus(), userId);

            if (notes == null)
            {
                return Error();
            }

            // Sorting:
            notes = _notesService.GetSortedNotes(_notesService.GetSortStatus(), notes);

            // Pagination:
            var data = _notesService.GetPagedNotes(notes, page, this);

            ViewBag.ErrorMessage = errorMessage;
            return View(data);
        }

        // GET: Notes/Details/5
        public async Task<IActionResult> Details(int? id) // TODO exception
        {
            try
            {
                var note = await _notesService.GetNoteAsync(id);

                if (note == null)
                {
                    return NotFound();
                }
                var wordCount = note.Contents.WordCount();
                ViewBag.Count = wordCount;
                ViewBag.NoteId = id;
                return View(note);
            }
            catch (NoteAccessDeniedException ex)
            {
                _logger.LogError($"Access to the note (Id: {ex.NoteId}) during {ex.Operation} operation was denied");
                return RedirectToAction(nameof(Index), new { errorMessage = ex.GetErrorMessage() });
            }
        }

        // GET: Notes/Create
        public async Task<IActionResult> Create()
        {
            IdentityUser user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return NotFound();
            }  

            var userId = user.Id;
            ViewBag.UserId = userId;

            return View();
        }

        public IActionResult Filter(NoteStatus? status)
        {
            _notesService.SetFilterStatus(status);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Search(string term)
        {
            if (!String.IsNullOrWhiteSpace(term))
            {
                var notes = await _notesService.GetIndexedNotesToListAsync(term);
                return View("Index", notes);
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Sort(int sortOrder)
        {
            _notesService.SetSortStatus(sortOrder);
            return RedirectToAction(nameof(Index));
        }

        // POST: Notes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Contents,Status, UserId")] CreateNoteRequest note)
        {
            if (ModelState.IsValid)
            {
                // the result is the ID of the created note
                int result = await _notesService.CreateNoteAsync(note);

                if (result > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                return Error();
            }
            return View(note);
        }

        // GET: Notes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                var note = await _notesService.GetNoteAsync(id);
                if (note == null)
                {
                    return NotFound();
                }

                return View(note);
            }
            catch (NoteAccessDeniedException ex)
            {
                _logger.LogError($"Access to the note (Id: {ex.NoteId}) during {ex.Operation} operation was denied");
                return RedirectToAction(nameof(Index), new { errorMessage = ex.GetErrorMessage() });
            }
        }

        public async Task<IActionResult> ExplainTask(string input)
        {
            string completionResult = await _openAIService.CompleteSentence(input);
            return Content(completionResult, "text/plain");
        }

        // POST: Notes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,Title,Contents,Status,AvgRating,UserId")] EditNoteRequest note)
        {
            if (ModelState.IsValid)
            {
                var result = await _notesService.UpdateNoteAsync(note);

                if (result)
                {
                    return RedirectToAction(nameof(Index));
                }
                return NotFound();
            }
            return View(note);
        }

        // GET: Notes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                var note = await _notesService.GetNoteAsync(id);

                if (note == null)
                {
                    return NotFound();
                }

                return View(note);
            }
            catch (NoteAccessDeniedException ex)
            {
                _logger.LogError($"Access to the note (Id: {ex.NoteId}) during {ex.Operation} operation was denied");
                return RedirectToAction(nameof(Index), new { errorMessage = ex.GetErrorMessage() });
            }
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(DeleteNoteRequest note)
        {
            var result = await _notesService.DeleteNoteAsync(note);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> SubmitRating(int rating, int noteId)
        {
            IdentityUser user = await _userManager.GetUserAsync(User);
            var note = await _notesService.GetNoteAsync(noteId);

            if (note != null)
            {
                var noteRatingId = _notesService.GetNoteRatingIdByUserId(note, user.Id);
                var result = await _ratingService.AddOrUpdateNoteRatingAsync(user.Id, note, noteRatingId, rating);

                if (result)
                {
                    var updatedNoteResult = await _notesService.CalculateAvgRating(note);

                    if (updatedNoteResult)
                    {
                        return RedirectToAction("Details", new { id = note.Id });
                    }
                }
            }
            return Error();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OnlineNotes/Views/Notes/Create.cshtml
@using OnlineNotes.Models.Enums;
@model OnlineNotes.Models.Note

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Note</h4>
<hr />
<div class="row">
    <div class="col-md-10">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contents" class="control-label"></label>
                <textarea asp-for="Contents" class="form-control" style="height:500px; resize:none"></textarea>
                <span asp-validation-for="Contents" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Status</label>
                <div>
                    @foreach (var status in Enum.GetValues(typeof(NoteStatus)))
                    {
                        <label class="radio-inline">
                            <input type="radio" asp-for="Status" value="@status" />
                            @status
                        </label>
                    }
                </div>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <input type="hidden" name="UserId" value="@ViewBag.UserId" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div asp-validation-summary="All" class="text-danger"></div>

<div>
    <a class="btn btn-secondary" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OnlineNotes/Views/Notes/Delete.cshtml
@using OnlineNotes.Models.Enums;
@model OnlineNotes.Models.Note

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

@*Makes the text warp to prevent horizontal scrolling*@
<style>
    pre {
        overflow-x: auto;
        white-space: pre-wrap;
    }
</style>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Note</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contents)
        </dt>
        <dd class = "col-sm-12">
            <pre>@Html.DisplayFor(model => model.Contents)</pre>
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a class="btn btn-secondary" asp-action="Index">Back to List</a>
    </form>
</div>

OnlineNotes/Views/Notes/Details.cshtml
@model OnlineNotes.Models.Note

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

@*Makes the text warp to prevent horizontal scrolling*@
<style>
    pre {
        overflow-x: auto;
        white-space: pre-wrap;
    }
</style>

<div>
    <h4>Note</h4>
    <hr />
    @if (Model.Ratings.Any())
    {
        <!--TODO rated by x users-->
        <p>Rating: @(Model.AvgRating.ToString())/5  Rated by: @(Model.Ratings.Count) @{
                if (Model.Ratings.Count == 1)
                {
                                    <text>user</text>
                } else
                {
                                    <text>users</text>
                }}
                </p>

    } else
    {
        <p>There are no ratings yet for this post</p>
    }
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contents)
        </dt>
        <dd class = "col-sm-12">
            <pre>@Html.DisplayFor(model => model.Contents)</pre>
        </dd>

        <div align="right" background: blue> @ViewBag.Count words</div>

        <div id="explainField" hidden>
            <dt class="col-sm-2">
                Explained like you're 5
            </dt>
            <dd class="col-sm-12" id="resultField">
                
            </dd>
        </div>

    </dl>
</div>

<div>
    <h4>Attachments</h4>
    <hr />
    @if (Model.Attachments.Any())
    {
        <p>Exist</p>
        <table class="table">
            <tbody>
                @foreach (var attachment in Model.Attachments)
                {
                    <tr>
                        <td>
                            @attachment.FilePath
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No attachments for this Note</p>
    }
    <a class="btn btn-primary mb-2" asp-action="Upload" asp-route-id="@Model.Id">Upload file</a>
    <hr />
</div>

<div>
    <h4>Rate this note</h4>

    <form asp-action="SubmitRating" asp-controller="Notes" method="post" onsubmit="return validateForm();" style="display: flex; flex-direction: row; align-items: flex-end;">
        <div class="stars" style="margin-right: 50px;">
        <input type="radio" id="star1" name="rating" value="1" />
        <input type="radio" id="star2" name="rating" value="2" />
        <input type="radio" id="star3" name="rating" value="3" />
        <input type="radio" id="star4" name="rating" value="4" />
        <input type="radio" id="star5" name="rating" value="5" />

        <label for="star1" aria-label="Banana">1 star</label>
        <label for="star2">2 stars</label>
        <label for="star3">3 stars</label>
        <label for="star4">4 stars</label>
        <label for="star5">5 stars</label>

        <input type="hidden" name="noteId" value="@Model.Id" />
    </div>
        <button type="submit" class="btn btn-dark btn-sm" style="width: 120px; height: 35px;">Submit</button>
    </form>

    <br />
    <hr />
</div>

<div>
    <h4>Comments</h4>
    <hr />
   
    @if (Model.Comments.Any())
    {
        <table class="table">
            <tr>
                <th></th>
                <th>Date Created</th>
                <th></th>
            </tr>
            <tbody>
            @foreach (var comment in Model.Comments)
            {
                <tr>
                    <td>
                        @comment.Contents
                    </td>
                    <td>
                        @comment.CreationDate
                    </td>
                    <td>
                            <a class="btn btn-danger btn-sm" asp-controller="Comments" asp-action="Delete" asp-route-Id="@comment.Id">Delete</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    } else
    {
        <p> There are no comments to display</p>
    }
</div>

<div>
    <button class="btn btn-info" id="explainButton" style="margin-bottom:10px">Explain it like im 5</button>
</div>
<div>
    <a class="btn btn-secondary" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
    <a class="btn btn-primary" asp-action="Index">Back to List</a>
    <a class="btn btn-outline-info" asp-controller="Comments" asp-action="Create" asp-route-noteId="@Model?.Id">Write a comment</a>
</div>

@section scripts {
    <script>
        document.getElementById("explainButton").addEventListener("click", function () {
            // Get the user input from the text input field
            var userInput = "explain it like im 5: @Model.Contents";

            // Send a request to the action with the user input
            fetch('@Url.Action("ExplainTask", "Notes")?input=' + encodeURIComponent(userInput))
                .then(response => response.text())
                .then(text => {
                    document.getElementById("explainField").removeAttribute("hidden");
                    // Display the returned text in the resultDiv
                    document.getElementById("resultField").innerText = text;
                })
                .catch(error => {
                    console.error('Error:', error);
                });
        });
    </script>

    <script>
        function validateForm() {
            var radioButtons = document.getElementsByName('rating');
            var radioButtonSelected = false;

            for (var i = 0; i < radioButtons.length; ++i) {
                if (radioButtons[i].checked) {
                    radioButtonSelected = true;
                    break;
                }
            }

            if (radioButtonSelected) {
                return true;
            }

            alert('Please select a rating before submitting')
            return false;
        }
    </script>
}

OnlineNotes/Views/Notes/Edit.cshtml
@model OnlineNotes.Models.Note
@using OnlineNotes.Models
@using OnlineNotes.Models.Enums;

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Note</h4>
<hr />
<div class="row">
    <div class="col-md-10">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="AvgRating" />
            <input type="hidden" asp-for="UserId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contents" class="control-label"></label>
                <textarea asp-for="Contents" class="form-control" style="height:500px; resize:none"></textarea>
                <span asp-validation-for="Contents" class="text-danger"></span>
            </div>
            <div style="margin-top:10px" class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-secondary" asp-action="Index">Back to List</a>
            </div>
            <div class="form-group">
                <label class="control-label">Status</label>
                <div>
                    @foreach (var status in Enum.GetValues(typeof(NoteStatus)))
                    {
                        <label class="radio-inline">
                            <input type="radio" asp-for="Status" value="@status" />
                            @status
                        </label>
                    }
                </div>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OnlineNotes/Views/Notes/Index.cshtml
@model IEnumerable<OnlineNotes.Models.Note>
@using OnlineNotes.Models.Enums;
@using OnlineNotes.Models.Pagination;

@{
    ViewData["Title"] = "Index";

    Pager pager = new Pager();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-dismissible alert-danger">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Error!</strong> @ViewBag.ErrorMessage
    </div>
}

<h1>Index</h1>

@*Makes the text warp to prevent horizontal scrolling*@
<style>
    pre {
        overflow-x: auto;
        white-space: pre-wrap;
    }

    .status-column {
        width: 50px; /* Adjust the width as needed */
    }

    #ellipsis {
        display: inline-block;
        width: auto;
        height: auto;
        max-height: 250px;
        width: 410px;
        overflow: auto;
        text-overflow: ellipsis;
    }
</style>

<p>
    <div class="btn-group" role="group">
        <a class="btn btn-primary" asp-action="Create" style="margin-right:100px">Create New</a>

        <button id="btnGroupDrop" type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="margin-right:10px">Sort by </button>
        <div class="dropdown-menu" aria-labelledby="btnGroupDrop">
            <a class="dropdown-item" asp-action="Sort" asp-route-sortOrder="0">Newest</a>
            <a class="dropdown-item" asp-action="Sort" asp-route-sortOrder="1">Oldest</a>
        </div>

        <button id="btnGroupDrop" type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Filter by </button>
        <div class="dropdown-menu" aria-labelledby="btnGroupDrop">
            <a class="dropdown-item" asp-action="Filter">All</a>
            <a class="dropdown-item" asp-action="Filter" asp-route-status="Public">Public</a>
            <a class="dropdown-item" asp-action="Filter" asp-route-status="Draft">Draft</a>
            <a class="dropdown-item" asp-action="Filter" asp-route-status="Archived">Archived</a>
        </div>

        <form class="d-flex" style="margin-left:10px" asp-action="Search">
            <input class="form-control me-sm-2" type="search" placeholder="Search" name="term">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>

        <a class="btn btn-link" asp-action="Filter">Show All</a>
    </div>
</p>
<table class="table">
    <thead>
    <tr>
        <th class="date-column">Date Created</th> <!-- Created Date column -->
        <th class="status-column">Status</th> <!-- Status column -->
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contents)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
                <td class="date-column" style="max-width: 300px">
                    @Html.DisplayFor(modelItem => item.CreationDate)
                </td>

                <td class="status-column">
                    @switch (item.Status)
                    {
                        case NoteStatus.Draft:
                            <span class="badge rounded-pill bg-light">@Html.DisplayFor(modelItem => item.Status)</span>
                            break;
                        case NoteStatus.Public:
                            <span class="badge rounded-pill bg-info">@Html.DisplayFor(modelItem => item.Status)</span>
                            break;
                        case NoteStatus.Archived:
                            <span class="badge rounded-pill bg-warning">@Html.DisplayFor(modelItem => item.Status)</span>
                            break;
                        default:
                            <span class="badge rounded-pill bg-danger">@Html.DisplayFor(modelItem => item.Status)</span>
                            break;
                    }
                </td>
            <td>
                    <pre style="max-width: 160px">@Html.DisplayFor(modelItem => item.Title)</pre>
            </td>
                <td>
                    <pre id="ellipsis">@Html.DisplayFor(modelItem => item.Contents)</pre>
            </td>
            <td>
                <div class="d-flex gap-1">
                    <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.Id">Details</a>
                    <a class="btn btn-info" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </div>
            </td>
        </tr>
    }
    </tbody>
</table>

<div class="container">
    @if (pager.TotalPages > 0)
    {
        <ul class="pagination justify-content-end">
            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
            {
                <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-controller="Notes" asp-action="Index" asp-route-page="@pge">
                        @pge
                    </a>
                </li>
            }
        </ul>
    }
</div>

OnlineNotes/Views/Notes/Upload.cshtml
@model OnlineNotes.Models.NoteAttachment
@using OnlineNotes.Models.Enums;

@{
    ViewData["Title"] = "Upload";
}

<h1>Upload file</h1>

<div class="mb-3 mt-3">
    <form asp-controller="Notes" asp-action="Upload" method="post" enctype="multipart/form-data">
        <div>
            <label class="form-label">Upload file</label>
            <input type="file" asp-for="File" class="form-control mb-2" />
        </div>
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>
</div>