OnlineNotes/Models/Quizzes/Question.cs
namespace OnlineNotes.Models.Quizzes
{
    public class Question
    {
        public int Id { get; set; } // primary key
        public int QuizId{ get; set; } // foreign key to Quiz
        public Quiz Quiz { get; set; } = null!; // navigation to principal
        public string QuestionText { get; set; } = null!;
        public List<QuestionOption> QuestionOptions { get; set; } = null!;
        public int? CorrectAnswer { get; set; } // index of the correct answer in QuestionOptions
        public bool? AnsweredCorrectly { get; set; }
        public string? Explanation { get; set; } // only if AnsweredCorrectly is false

    }
}

OnlineNotes/Models/Quizzes/QuestionOption.cs
namespace OnlineNotes.Models.Quizzes
{
    public class QuestionOption
    {
        public int Id { get; set; }
        public int QuestionId { get; set; } // foreign key to Question
        public Question Question { get; set; } = null!; // navigation to principal
        public string OptionText { get; set; } = null!;
    }
}

OnlineNotes/Models/Quizzes/Quiz.cs
using OnlineNotes.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace OnlineNotes.Models.Quizzes
{
    public class Quiz
    {
        public int Id { get; set; } // primary key
        public string UserId { get; set; } = null!;
        public DateTime CreationDate { get; set; }
        [StringLength(60, ErrorMessage = "Title length must not exceed 60 characters")]
        public string Title { get; set; } = null!;
        public string NoteContents {  get; set; } = null!;
        public QuizDifficulty Difficulty { get; set; }
        [Range(2, 5, ErrorMessage = "Number of questions must be between 2 and 5")]
        public int QuestionsCount { get; set; }
        public ICollection<Question> Questions { get; } = new List<Question>();
        public int? Score { get; set; }
        public bool IsCompleted { get; set; }

        public Quiz()
        {

        }
        public Quiz(string userId, DateTime creationDate, string title, string noteContents, QuizDifficulty difficulty, int questionsCount)
        {
            UserId = userId;
            CreationDate = creationDate;
            Title = title;
            NoteContents = noteContents;
            Difficulty = difficulty;
            QuestionsCount = questionsCount;
        }
    }
}

OnlineNotes/Controllers/QuizzesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineNotes.ExtensionMethods;
using OnlineNotes.Models.Quizzes;
using OnlineNotes.Models.Requests.Quiz;
using OnlineNotes.Services.NotesServices;
using OnlineNotes.Services.QuizzesServices;

namespace OnlineNotes.Controllers
{
    [Authorize]
    public class QuizzesController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ILogger<QuizzesController> _logger;
        private readonly IQuizzesService _quizzesService;
        private readonly INotesService _notesService;

        public QuizzesController(UserManager<IdentityUser> userManager, ILogger<QuizzesController> logger, IQuizzesService quizzesService, INotesService notesService)
        {
            _userManager = userManager;
            _logger = logger;
            _quizzesService = quizzesService;
            _notesService = notesService;
        }

        public async Task<IActionResult> Index()
        {
            var quizzes = await _quizzesService.GetAllQuizzesToListAsync();
            if (quizzes == null)
            {
                return NotFound();
            }
            return View(quizzes);
        }

        public async Task<IActionResult> Create(string? errorMsg = null)
        {
            IdentityUser user = await _userManager.GetUserAsync(User);
            var userId = user.Id;
            ViewBag.UserId = userId;
            ViewBag.ErrorMsg = errorMsg;
            var notes = await _notesService.GetAllNotesToListAsync();
            if (notes != null && notes.Any())
            {
                ViewBag.Notes = notes;
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Quiz quiz)
        {
            quiz.CreationDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                var noteWordCount = quiz.NoteContents.WordCount();
                if (noteWordCount > 500)
                {
                    return RedirectToAction("Create", new { errorMsg = "Your selected note should contain no more than 500 words" });
                }

                CreateQuizRequest quizRequest = new()
                {
                    UserId = quiz.UserId,
                    CreationDate = quiz.CreationDate,
                    Title = quiz.Title,
                    NoteContents = quiz.NoteContents,
                    Difficulty = quiz.Difficulty,
                    QuestionsCount = quiz.QuestionsCount
                };
                var quizeId = await _quizzesService.CreateQuizAsync(quizRequest);
                if (quizeId != null && quizeId > 0)
                {
                    return RedirectToAction("QuizAttempt", new { id = quizeId });
                }

                return RedirectToAction("Create", new {errorMsg = "Something went wrong while generating your quiz. Please try again later or adjust the quiz generation configuration" });
            }
            return View(quiz);
        }

        public async Task<IActionResult> QuizAttempt(int id)
        {
            var quiz = await _quizzesService.GetQuizByIdAsync(id);
            if (quiz != null && id >= 0)
            {
                return View(quiz);
            }

            return NotFound();
        }

        [HttpPost]
        [Route("Quizzes/SubmitAnswers")]
        public async Task<IActionResult> SubmitAnswers(IFormCollection formCollection)
        {
            List<int> answers = new();
            int quizId = 0;
            foreach (var key in formCollection.Keys)
            {
                if (key.StartsWith("question_"))
                {
                    var questionId = key.Substring("question_".Length);
                    var selectedOptionId = formCollection[key];
                    if (!string.IsNullOrEmpty(selectedOptionId))
                    {
                        answers.Add(int.Parse(selectedOptionId));
                    }
                    
                }
                if(key.Equals("QuizId"))
                {
                    quizId = int.Parse(formCollection[key]);
                }
            }
            if (answers.Any() && quizId > 0)
            {
                var result = await _quizzesService.EvaluateQuiz(answers, quizId);
                if (result == true)
                {
                    return RedirectToAction("Details", new { id = quizId });
                }
            }
            return RedirectToAction("Index");
        }

        [HttpDelete]
        [Route("Quizzes/Delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            var result = await _quizzesService.DeleteQuizAsync(id);
            if (result == true)
            {
                return RedirectToAction("Index");
            } else
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            var quiz = await _quizzesService.GetQuizByIdAsync(id);
            if (quiz != null && id >= 0)
            {
                return View(quiz);
            }

            return NotFound();
        }
    }
}

OnlineNotes/Views/Quizzes/Create.cshtml
@using OnlineNotes.Models.Enums
@model OnlineNotes.Models.Quizzes.Quiz

@{
    ViewData["Title"] = "Create";
}

<style>
    .main-container {
        margin-bottom: 200px;
    }
</style>

<style>
    .scrollable-notes { /* This is the scrollable div for notes selection */
        max-height: 200px;
        overflow-y: auto;
        border: 1px solid #ccc;
        padding: 10px;
    }
</style>

@if (ViewBag.ErrorMsg != null)
{
    <div class="alert alert-dismissible alert-danger">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Oops!</strong> @ViewBag.ErrorMsg
    </div>
}

<h1>Generate a new quiz</h1>

<div class="row justify-content-center align-items-center main-container" style="height: 50vh;">
    <div class="col-md-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Title" class="control-label"><h5>Quiz Title:</h5></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <br />

            <div class="form-group">
                <label asp-for="Difficulty" class="control-label"><h5>Difficulty:</h5></label>
                <div>
                    @foreach (QuizDifficulty difficulty in Enum.GetValues(typeof(QuizDifficulty)))
                    {
                        <label class="radio-inline">
                            @if (difficulty != QuizDifficulty.Easy)
                            {
                                <input type="radio" asp-for="Difficulty" value="@difficulty" disabled="disabled" />
                            }
                            else
                            {
                                <input type="radio" asp-for="Difficulty" value="@difficulty" />
                            }
                            @difficulty
                        </label>
                    }
                </div>
                <span asp-validation-for="Difficulty" class="text-danger"></span>
            </div>
            <br />

            <div class="form-group">
                <label asp-for="QuestionsCount" class="control-label"><h5>Number of Questions:</h5></label>
                <input asp-for="QuestionsCount" type="number" class="form-control" />
                <span asp-validation-for="QuestionsCount" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label><h5>Include Notes:</h5></label>
                <div class="scrollable-notes">
                    @if (ViewBag.Notes != null)
                    {
                        @foreach (var note in ViewBag.Notes)
                        {
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="NoteContents" value="@note.Contents">
                                <label class="form-check-label">
                                    @note.Title
                                </label>
                            </div>
                        }
                    }
                </div>
            </div>

            <input type="hidden" asp-for="UserId" value="@ViewBag.UserId" />

            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-group">
                <input type="submit" value="Generate" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

OnlineNotes/Views/Quizzes/Details.cshtml
@model OnlineNotes.Models.Quizzes.Quiz
@{
    ViewData["Title"] = "Details";
}

<h3>Answered Correctly: @Model.Score / @Model.QuestionsCount</h3>

<table class="table">
    <thead>
        <tr class="table-primary">
            <th></th> <!-- Correct/Not correct -->
            <th></th> <!-- Question -->
        </tr>
    </thead>
    <tbody>
        @foreach (var question in Model.Questions)
        {
            @if (question.AnsweredCorrectly.HasValue && question.AnsweredCorrectly == true)
            {
                <tr class="table-success">
                    @{
                        var selectedOption = question.AnsweredCorrectly.HasValue ? question.AnsweredCorrectly.Value ? "✔" : "❌" : "";
                    }
                    <td>@selectedOption</td>

                    <td>@question.QuestionText</td>
                </tr>
            } else
            {
                <tr class="table-danger">
                    @{
                        var selectedOption = question.AnsweredCorrectly.HasValue ? question.AnsweredCorrectly.Value ? "✔" : "❌" : "";
                    }
                    <td>@selectedOption</td>

                    <td>@question.QuestionText</td>
                </tr>
            }
        }
    </tbody>
</table>

<div>
    <a class="btn btn-info" asp-action="QuizAttempt" asp-route-id="@Model?.Id">Try again</a>
    <a class="btn btn-primary" asp-action="Index">Back to List</a>
</div>

OnlineNotes/Views/Quizzes/Index.cshtml
@model IEnumerable<OnlineNotes.Models.Quizzes.Quiz>

@{
    ViewData["Title"] = "Index";
}

<div style="text-align: center; margin-top: 20px;">
    <br />
    <a class="btn btn-primary" asp-action="Create">+ create a new quiz</a>
    <hr />
</div>
<div>
    @if (!Model.Any())
    {
        <h3>There are no quizzes yet. Feel free to create one</h3>
    }
    else
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Difficulty</th>
                    <th>Score</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var quiz in Model)
                {
                    <tr>
                        <td><h6>@quiz.Title</h6></td>
                        <td> <span class="badge bg-light">@quiz.Difficulty</span></td>
                        <!-- <td>@quiz.Score</td> -->
                        <td>
                            <h5>
                            @if (quiz.Score != null && quiz.QuestionsCount > 0)
                            {
                                var percentage = ((double)quiz.Score / quiz.QuestionsCount) * 100;
                                @percentage.ToString("0.##")
                            }
                            else
                            {
                                @("—")
                            }
                            %
                            </h5>
                        </td>
                        <td class="text-end">
                            <div class="d-flex gap-1 justify-content-end">
                                @if (quiz.Score != null)
                                {
                                    <a class="btn btn-success" asp-action="Details" asp-route-id="@quiz.Id">Results</a>
                                }
                                else
                                {
                                    <a class="btn btn-success disabled" asp-action="Details" asp-route-id="@quiz.Id">Results</a>
                                }
                                <a class="btn btn-info" asp-action="QuizAttempt" asp-route-id="@quiz.Id">Solve</a>
                                <button class="btn btn-danger delete-btn" data-bs-toggle="modal" data-bs-target="#deleteModal" data-bs-id="@quiz.Id">Delete</button>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

<!-- The Modal -->
<div class="modal" id="deleteModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Are you sure you want to delete this quiz?</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="quizId" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" onclick="deleteQuiz()">Delete</button>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        $('#deleteModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var quizId = button.data('bs-id');
            $('#quizId').val(quizId);
        });

        function deleteQuiz() {
            // Retrieve the quiz id from the modal content
            var quizId = $('#quizId').val();
            var url = '@Url.Action("Delete", "Quizzes")/' + quizId;
            // Perform the delete operation using AJAX
            $.ajax({
                url: url,
                type: 'DELETE',
                data: { id: quizId },  // Add this line to pass the ID as data
                success: function (data) {
                    // Handle success (if needed)
                    console.log('Quiz deleted successfully.');
                    // Reload the page or update the UI as needed
                    location.reload();
                },
                error: function (error) {
                    // Handle error (if needed)
                    console.error('Error deleting quiz:', error);
                },
                complete: function () {
                    // Close the modal regardless of success or failure
                    $('#deleteModal').modal('hide');
                }
            });
        }
    </script>
}

OnlineNotes/Views/Quizzes/QuizAttempt.cshtml
@model OnlineNotes.Models.Quizzes.Quiz

@{
    ViewData["Title"] = "QuizAttempt";
}

<h1>Solve a quiz</h1>
<br />

<div>
    <p><h5>Title:</h5> @Model.Title </p>
    <p><h5>Difficulty:</h5> @Model.Difficulty</p>
    <br />
    <!--
    <p><h5>Quiz:</h5> @Model.NoteContents</p>
    -->
</div>

<div>
    <form method="post" asp-action="SubmitAnswers">
        @foreach (var question in Model.Questions)
        {
            <div>
                <fieldset id="question_@question.Id">
                    <p><h5>Question:</h5> <h6>@question.QuestionText</h6></p>
                    @for (int i = 0; i < question.QuestionOptions.Count; ++i)
                    {
                       var option = question.QuestionOptions[i];
                        <label>
                            <input type="radio" name="question_@question.Id" value="@i" />
                            @option.OptionText
                        </label>
                        <br />
                    }

                </fieldset>
            </div>
            <hr />
        }
        <input type="hidden" name="QuizId" value="@Model.Id" />
        <button type="submit" class="btn btn-primary">Submit answers</button>
    </form>
</div>

<div>
    <hr />
    <a class="btn btn-primary" asp-action="Index">Back to List</a>
</div>